### ISSUE TITLE
Typing effect by just using css 

### ISSUE THREAD

**Issue by CS50X-RGB** [ismeet010/Magic-Of-CSS#33]
Creating typing animation using css

**Comment by CS50X-RGB** [comment]
@ismeet010 pls assign this issue to me

**Comment by yosaami** [comment]
I have already created this effect using CSS, please assign me under hacktoberfest tag.

**Comment by CS50X-RGB** [comment]
I have also done made this animation not this fair that i get the issue

**Comment by CS50X-RGB** [comment]
@ismeet010 made the pr too plz check
